language: ruby
sudo: false
dist: xenial
rvm:
  - 2.4.1
warnings_are_errors: false

notifications:
  slack: ie-lab:GtXnNyh9RcsGDWNeubYlIIJn   

before_install:
  - sudo apt-get install -y lftp
  - sudo /sbin/modprobe tun
  - sudo apt-get install network-manager-openconnect-gnome

install:
  - gem install jekyll bundler
  - bundle install

script: bundle exec jekyll build

cache: bundler # caching bundler gem packages will speed up build

after_success:
  - echo $PASS | sudo openconnect rpv.usherbrooke.ca --user=view2301 --background --passwd-on-stdin
  - cp _site/home/index.html _site/index.html
  - chmod +x script/deploy.sh
  - bash script/deploy.sh
