language: ruby
sudo: false 
rvm:
  - 2.4.1
warnings_are_errors: false

notifications:
  email:
    recipients:
      - s.vissault@yahoo.fr

before_install:
  - sudo apt-get install -y libcurl4-openssl-dev

install: gem install jekyll jekyll-sitemap jekyll-scholar

script: jekyll build

after_script:
 - cp _site/home/index.html index.html

cache: bundler # caching bundler gem packages will speed up build
