language: ruby
sudo: false
dist: xenial
rvm:
  - 2.4.1
warnings_are_errors: false

notifications:
  email:
    recipients:
      - s.vissault@yahoo.fr
      - w.vieiraw@gmail.com

before_install:
  - sudo apt-get install -y lftp

install:
  - gem install jekyll bundler
  - bundle install

script: bundle exec jekyll build

cache: bundler # caching bundler gem packages will speed up build

# after_success:
#   - cp _site/home/index.html _site/index.html
#   - chmod +x script/deploy.sh
#   - bash script/deploy.sh
