name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 1

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      
      - name: 🔧 Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          sudo /sbin/modprobe tun
          sudo apt-get install network-manager-openconnect-gnome

      - name: 🔨 Build site
        uses:  lemonarc/jekyll-action@1.0.0
      
      - name: Prepare deployment
        run: cp _site/home/index.html _site/index.html

      - name: 🚀 Deploy gh_pages
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: _site
          single-commit: true
