name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 1

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      
      - name: 🔧 Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo apt-get install -y lftp
          sudo /sbin/modprobe tun
          sudo apt-get install network-manager-openconnect-gnome

      - name: 🔨 Build site
        uses:  lemonarc/jekyll-action@1.0.0
      
      - name: 🚀 Deploy
        run: |
          echo ${{ secrets.PASS }} | sudo openconnect rpv.usherbrooke.ca --user=view2301 --background --passwd-on-stdin
          sudo cp _site/home/index.html _site/index.html
          lftp -d -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} ${{ secrets.FTP_SITE }}:21 -e 'set ftp:passive-mode on; set ssl:verify-certificate no; debug 9; mirror --ignore-time --parallel=10 -e -v -R _site ~ ; exit'

